# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
    
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: CmdLine@2
  inputs:
    script: |
       docker run -p 5432:5432 -d --name db arminc/clair-db:latest
       docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:latest  docker images
       docker images
       docker ps
       ip a
      
- task: CmdLine@2
  inputs:
    script: |
      curl -L https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_386 -o /usr/local/bin/clair-scanner
      chmod +x /usr/local/bin/clair-scanner
      docker pull nginx
      clair-scanner -h
      clair-scanner  --ip 3.85.232.123 nginx
      
       
