# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CmdLine@2
  inputs:
     script: |
       sudo apt-get update -y
       sudo apt-get -y upgrade
       cd /tmp
       wget https://dl.google.com/go/go1.11.linux-amd64.tar.gz
       sudo tar -xvf go1.11.linux-amd64.tar.gz
       sudo mv go /usr/local
       export GOROOT=/usr/local/go
       export GOPATH=$HOME/go
       export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
- task: CmdLine@2
  inputs:
    script: |
      # Clone the repo
      git clone https://github.com/sekharreddy0463/clair-scanner.git
      # Build and install 
      cd clair-scanner
      make build
      make installLocal
      ls
      # Run
      #./clair-scanner -h
       ./example-run.sh
       
